vich_uploader:
    db_driver: orm

    mappings:
        imageuploads:
           uri_prefix: /uploads/
           upload_destination: '%kernel.project_dir%/public/uploads/'
        imageuploads1:
           uri_prefix: /uploads/
           upload_destination: '%kernel.project_dir%/public/uploads1/'
